ft(google-auth): allow a user to login using google [187364805]
atlp-rwanda/e-commerce-serge-30-fn pull request #10
Opened 2024-06-17 18:30 UTC by Aldot-02

- A user should be able to login using google

2024-06-21 10:07 UTC, tuyishimehope approved these changes
LGTM

2024-06-21 10:16 UTC, martinemahirwe approved these changes
LGTM

2024-06-21 10:47 UTC, tuyishimehope approved these changes
LGTM

2024-06-21 10:47 UTC, martinemahirwe approved these changes
LGTM

2024-06-21 12:30 UTC, SergeInGithub requested changes
Nice work so far... In addition to the reviews below, Improve all components and add another prop to them for classnames... such that one can modify the preconfigured styles of the component with their own. @Aldot-02

2024-06-21 12:30 UTC, SergeInGithub commented on src/components/authcomponents/GoogleBtn.tsx
> +        'https://staging-e-commerce-serge-30-bn.onrender.com/api/v1/auth/google/callback',
Let's not expose these URLs... use .env

2024-06-21 14:36 UTC, Aldot-02 commented
> Nice work so far... In addition to the reviews below, Improve all components and add another prop to them for classnames... such that one can modify the preconfigured styles of the component with their own. @Aldot-02

@SergeInGithub, I adjusted this for the google button component as the other components are dummy, but I communicated to @martinemahirwe who is working on signup using real components to consider this suggestion.

2024-06-21 14:57 UTC, tuyishimekyrie approved these changes
LGTM

2024-06-24 07:00 UTC, SergeInGithub approved these changes
LGTM

2024-06-24 07:00 UTC, merged