feat(login.page)prompt-change-pwd-on-expired-pwd-[187364810]
atlp-rwanda/e-commerce-serge-30-fn pull request #11
Opened 2024-06-18 07:47 UTC by shebz2023

**what does this PR do?**

this Pr adds an interface that tells users with expired password to change their password or to explore without loging in for their security.

**what are relevant pivotal tracker id?**
187364810

2024-06-29 07:31 UTC, martinemahirwe submitted a review, later dismissed
Good work @shebz2023

2024-06-29 09:29 UTC, Sagastein submitted a review, later dismissed
LGTM 🆗

2024-06-30 18:50 UTC, SergeInGithub requested changes
Address the minor change below and you're good

2024-06-30 18:50 UTC, SergeInGithub commented on src/pages/authpages/RequestPwdChangePage.tsx
> +      ></div>
```suggestion
      <div 
        className="hidden lg:block lg:w-1/2 bg-cover bg-center h-screen" role='image'
        style={{ backgroundImage: `url(${leftImage})` }}
      />
```

2024-07-01 15:07 UTC, SergeInGithub approved these changes
LGTM

2024-07-01 15:08 UTC, merged