ft(updatepasssword): user can update their password [#187364862]
atlp-rwanda/e-commerce-serge-30-fn pull request #13
Opened 2024-06-18 09:03 UTC by Oliviier-dev

This PR adds an interface to allow users to update their password.

2024-06-29 19:16 UTC, tuyishimekyrie approved these changes, later dismissed
LGTM

2024-06-29 20:00 UTC, shebz2023 submitted a review, later dismissed
LGTM

2024-06-30 18:18 UTC, SergeInGithub requested changes
Nice work so far. Some reviews below @Oliviier-dev

2024-06-30 18:18 UTC, SergeInGithub commented on src/components/rootcomponents/Sidebar.tsx
> +];
Put this in the data folder under source. create a file there with relevant name, export it and use it here

2024-06-30 19:34 UTC, SergeInGithub approved these changes
LGTM

2024-06-30 19:34 UTC, merged