ft(TwoFactorAuth.tsx): Add two factor authentication for login process
atlp-rwanda/e-commerce-serge-30-fn pull request #14
Opened 2024-06-18 14:47 UTC by tuyishimekyrie

2024-06-28 13:55 UTC, Ke-bean reviewed
Great work @tuyishimekyrie , Some minor changes below!

2024-06-28 13:55 UTC, Ke-bean commented on src/components/rootcomponents/NavBar.tsx
> +            <svg
Let's use an Input Component here

2024-06-28 13:55 UTC, Ke-bean commented on src/components/rootcomponents/ProductList.tsx
> +          </button>
Here also, let's use a Button Component

2024-06-28 13:55 UTC, Ke-bean commented on src/components/rootcomponents/ShopProduct.tsx
> +            </button>
Here also, let's use Button Component

2024-06-28 13:55 UTC, Ke-bean commented on src/pages/auth/TwoFactorAuth.tsx
> +        />
same here, Input Component

2024-06-28 13:55 UTC, Ke-bean commented on src/pages/auth/TwoFactorAuth.tsx
> +          </button>
lets use Button Component

2024-06-28 13:55 UTC, Ke-bean commented on src/pages/rootpages/Home.tsx
> +          </button>
Same here!

2024-06-28 14:22 UTC, Sagastein requested changes
great hope just a few changes you can put all this backend **URL** in the .env

2024-06-28 14:22 UTC, Sagastein commented on src/components/usercomponents/VendorRedirection.ts
> +      {
you can put this URL in Env variable

2024-06-28 14:22 UTC, Sagastein commented on src/components/usercomponents/VendorRedirection.ts
> +      {
use env

2024-06-28 14:22 UTC, Sagastein commented on src/pages/auth/TwoFactorAuth.tsx
> +        {
use env

2024-06-29 09:24 UTC, Sagastein submitted a review, later dismissed
LGTM 👌

2024-06-29 09:40 UTC, Ke-bean submitted a review, later dismissed
LGTM

2024-06-29 10:07 UTC, Ke-bean submitted a review, later dismissed
LGTM

2024-06-29 10:11 UTC, Sagastein approved these changes, later dismissed
look great

2024-06-29 11:02 UTC, Ke-bean submitted a review, later dismissed
Great work

2024-06-29 20:43 UTC, SergeInGithub requested changes
Look into the reviews below @tuyishimekyrie

2024-06-29 20:43 UTC, SergeInGithub commented on src/components/authcomponents/GoBackButton.tsx
> +export default GoBackButton;
Don't we already have a button component?

2024-06-29 20:43 UTC, SergeInGithub commented on src/components/rootcomponents/Footer.tsx
> +          </div>
You're repeating yourself here. This could be a component

2024-06-29 20:43 UTC, SergeInGithub commented on src/components/rootcomponents/HeroShowProduct.tsx
> +];
Put this in a separate ts file in the data folder under src

2024-06-29 20:43 UTC, SergeInGithub commented on src/components/rootcomponents/ProductMarquee.tsx
> +
separate ts file in the data folder

2024-06-29 20:43 UTC, SergeInGithub commented on src/components/rootcomponents/ShopProduct.tsx
> +];
Same here!

2024-06-29 20:43 UTC, SergeInGithub commented on src/pages/auth/TwoFactorAuth.tsx
> +          </button>
Use the button component here as well

2024-06-29 20:43 UTC, SergeInGithub commented on src/pages/rootpages/Home.tsx
> +            </div>
This should be a component! You're repeating yourself

2024-06-29 20:43 UTC, SergeInGithub commented on src/pages/rootpages/Home.tsx
> +          </div>
This should be a component!

2024-06-29 20:43 UTC, SergeInGithub commented on src/pages/rootpages/Home.tsx
> +        </div>
Component here as well!

2024-06-30 11:03 UTC, Sagastein requested changes
Great Job @tuyishimekyrie as @SergeInGithub  suggested you can also add this constant data in the folder for data instead of putting them together with the component

2024-06-30 11:03 UTC, Sagastein commented on src/components/rootcomponents/HomeReviews.tsx
> +  },
you can also add this in data folder

2024-06-30 11:03 UTC, Sagastein commented on src/components/rootcomponents/MoreServices.tsx
> +];
same here you can separate this constants in different file as this for a react component

2024-06-30 13:23 UTC, Sagastein approved these changes, later dismissed
LGTM 👍

2024-06-30 20:27 UTC, Sagastein approved these changes, later dismissed
good

2024-07-01 08:24 UTC, Ke-bean submitted a review, later dismissed
Good work

2024-07-01 08:49 UTC, andremugabo approved these changes, later dismissed
LGTM

2024-07-01 15:04 UTC, SergeInGithub requested changes
Please address the changes you've been requested! @tuyishimekyrie

2024-07-01 15:04 UTC, SergeInGithub commented on src/data/index.ts
> +export * from './sidebarLinks';
You should export all files within the data directory here. footerdata, heroproducts, maqueedata... Haven't i said this already?

2024-07-01 15:04 UTC, SergeInGithub commented on src/components/rootcomponents/FeatureSection.tsx
> +];
Should go in the data folder!

2024-07-02 07:10 UTC, SergeInGithub approved these changes
LGTM

2024-07-02 07:13 UTC, merged