ft(auth.tsx):Allow users to login with email and password[187364806]
atlp-rwanda/e-commerce-serge-30-fn pull request #15
Opened 2024-06-19 09:05 UTC by Ke-bean

To be able to use the application and access authenticated routes, a login form should be presented to users and users should be able to login with email and password

2024-06-26 04:55 UTC, tuyishimekyrie submitted a review, later dismissed
LGTM

2024-06-26 09:32 UTC, shebz2023 reviewed
Great job !@Ke-bean ,its better if we return the response to the user, 'toast'library may help

2024-06-26 09:32 UTC, shebz2023 commented on src/components/usercomponents/LoginForm.tsx
> +const LoginForm = () => {
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

2024-06-26 09:32 UTC, shebz2023 commented on src/components/usercomponents/LoginForm.tsx
> +        <form className="flex flex-col bg-white-100  px-8 pt-6 pb-6 my-2 w-full max-w-md">
"ToastContainer />"

2024-06-26 09:48 UTC, shebz2023 submitted a review, later dismissed
LGTM

2024-06-26 09:48 UTC, martinemahirwe submitted a review, later dismissed
LGTM

2024-06-26 13:32 UTC, SergeInGithub requested changes
Look into the reviews below @Ke-bean

2024-06-26 13:32 UTC, SergeInGithub commented on src/components/usercomponents/LoginForm.tsx
> +            <button className="bg-black hover:bg-gray-500  font-bold py-1 px-4 rounded focus:outline-none focus:shadow-outline hover:bg-black hover:text-white w-full bg-gray-100 text-black flex flex-
These buttons almost have the same classes. Can't you make this a component or use the already existing button component and extra classes needed through the className prop?

2024-06-26 13:32 UTC, SergeInGithub commented on src/components/rootcomponents/Input.tsx
> +    <div className={`mb-4 ${className}`}>
I think we might need this className more on the input than here. Or you can add another one

2024-06-26 14:50 UTC, tuyishimekyrie submitted a review, later dismissed
LGTM

2024-06-27 10:41 UTC, tuyishimekyrie submitted a review, later dismissed
LGTM

2024-06-27 10:43 UTC, shebz2023 submitted a review, later dismissed
LGTM

2024-06-27 10:54 UTC, shebz2023 approved these changes, later dismissed

2024-06-27 10:55 UTC, martinemahirwe approved these changes, later dismissed
LGTM

2024-06-27 11:01 UTC, tuyishimekyrie submitted a review, later dismissed
LGTM

2024-06-27 17:49 UTC, tuyishimekyrie approved these changes, later dismissed
LGTM

2024-06-27 17:55 UTC, shebz2023 approved these changes, later dismissed
LGTM

2024-06-27 18:07 UTC, SergeInGithub requested changes
Nice work so far. Some reviews below @Ke-bean

2024-06-27 18:07 UTC, SergeInGithub commented on src/components/Input.tsx
> +      className="rounded-[8px] w-[60%] border border-[#E0E0E0] py-2 px-4 box-border text-[#828282] shadow-sm focus:outline-none font-medium text-[16px]"
I believe we had a className prop here. if not add it

2024-06-27 18:07 UTC, SergeInGithub commented on src/components/rootcomponents/Header.tsx
> +          </button>
We have a button component

2024-06-27 18:07 UTC, SergeInGithub commented on src/components/rootcomponents/LoginInput.tsx
> +export default Input;
Can't we have one input which can be reusable everywhere? Why make another component here when we already had it?

2024-06-27 18:07 UTC, SergeInGithub commented on src/hooks/useForgotPassword.ts
> +     );
This is not how we're communicating with the backend. we have redux for this

2024-06-27 18:08 UTC, martinemahirwe approved these changes, later dismissed
LGTM

2024-06-28 09:20 UTC, tuyishimekyrie submitted a review, later dismissed
LGTM

2024-06-28 09:33 UTC, shebz2023 approved these changes
LGTM

2024-06-28 09:33 UTC, tuyishimekyrie approved these changes
LGTM

2024-06-28 09:34 UTC, martinemahirwe approved these changes
LGTM

2024-06-28 09:54 UTC, SergeInGithub approved these changes
LGTM

2024-06-28 09:54 UTC, merged