ft(Creating-Product): Allow a seller to create/add a product
atlp-rwanda/e-commerce-serge-30-fn pull request #19
Opened 2024-06-27 10:09 UTC by Aldot-02

## ℹ️ Description

As a Seller

- I should be able to add/create items for sale
- This page should only be accessible to sellers, i.e authenticated
- Such that the stock can be seen by any requesting client
- Handle all responses and errors from the backend

##### 📹 Loom video link: Not available yet

## 🧪 How can this be tested?

This should be tested on the vendor dashboard, under the route of vendor/create that can be accessed by clicking the Add product button.

## 📸 Screenshots

<img width="1440" alt="Screenshot 2024-06-27 at 12 06 47" src="https://github.com/atlp-rwanda/e-commerce-serge-30-fn/assets/114801675/813e56ef-9954-42ca-a417-d27ff101484c">

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-09 12:59 UTC, martinemahirwe submitted a review, later dismissed
LGTM

2024-07-09 13:01 UTC, Oliviier-dev approved these changes, later dismissed
LGTM

2024-07-09 16:07 UTC, SergeInGithub requested changes
Nice work so far. Look into some reviews below @Aldot-02

2024-07-09 16:07 UTC, SergeInGithub commented on src/components/ToastMessage.tsx
> +        </button>
We have a button component that can be used here

2024-07-09 16:07 UTC, SergeInGithub commented on src/pages/vendorpages/addProducts.tsx
> +          </button>
We have a button component that can be used or improved if it's not dynamic enough

2024-07-09 21:58 UTC, martinemahirwe approved these changes, later dismissed
LGTM

2024-07-10 03:08 UTC, Oliviier-dev submitted a review, later dismissed
LGTM

2024-07-10 12:53 UTC, martinemahirwe approved these changes
LGTM

2024-07-10 16:35 UTC, SergeInGithub approved these changes
LGTM

2024-07-10 16:35 UTC, merged