chore(.husky)configure-eslint-precommithook for test and formatting
atlp-rwanda/e-commerce-serge-30-fn pull request #2
Opened 2024-06-12 09:15 UTC by shebz2023

**what does this Pr do?**
this pr add a precommit hook to run eslint format and test

**how does this pr achieve this**
it uses husky for hooks,eslint with rules like _doublequotes_,_no unused vars_ and more

**what are the relevant pivotal tracker id**
#187364801

2024-06-12 17:33 UTC, andremugabo approved these changes
LGTM

2024-06-12 20:15 UTC, Aldot-02 approved these changes
LGTM

2024-06-13 06:41 UTC, SergeInGithub requested changes
Looks good. Can you also configure prettier, as you can see you're touching files that you didn't intend to change because you're changing singlequotes to double, add prettier to prevent this and other unintended changes. @shebz2023

2024-06-13 13:36 UTC, SergeInGithub requested changes
Change the minor configuration below @shebz2023

2024-06-13 13:36 UTC, SergeInGithub commented on .prettierrc
> +    "singleQuote": false,
```suggestion
    "singleQuote": true,
```

2024-06-13 14:51 UTC, SergeInGithub reviewed
Looks good. Just rebase

2024-06-14 10:00 UTC, SergeInGithub approved these changes
LGTM

2024-06-14 10:00 UTC, merged