ft(userProfilePage):User can view and edit their profile[#187364815]
atlp-rwanda/e-commerce-serge-30-fn pull request #23
Opened 2024-07-01 15:29 UTC by Ke-bean

## ℹ️ Description

Users should be able to amend/edit their profiles depending on a change of preference
 to the entire disclosure of the individual user

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

This can be tested by accessing the Authenticated user dashboard and view && edit profile as needed

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-09 15:24 UTC, Oliviier-dev reviewed
Great work @Ke-bean, work on this minor change below:

2024-07-09 15:24 UTC, Oliviier-dev commented on src/components/authcomponents/editProfile.tsx
> +    }
It would be better if we displayed the error message with toast.

2024-07-09 22:30 UTC, andremugabo approved these changes, later dismissed
LGTM

2024-07-10 03:09 UTC, Oliviier-dev approved these changes, later dismissed
LGTM

2024-07-10 08:02 UTC, SergeInGithub requested changes
Work on the review below and you're good

2024-07-10 08:02 UTC, SergeInGithub commented on src/components/rootcomponents/MenuLinksIcons.tsx
> +    console.log('Hello world');
```suggestion
```

2024-07-10 08:42 UTC, SergeInGithub approved these changes
LGTM

2024-07-10 08:42 UTC, merged