Add role based access control functionality(RBAC)
atlp-rwanda/e-commerce-serge-30-fn pull request #25
Opened 2024-07-02 15:03 UTC by tuyishimekyrie

## ℹ️ Description

Please write about the changes implemented in this PR. Also write a short description about why the change is implemented.

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-04 18:13 UTC, Oliviier-dev reviewed
Good job far, work on the tests as well as the review down below

2024-07-04 18:13 UTC, Oliviier-dev commented on src/layouts/AdminLayout.tsx
Restrict access to admin pages to ensure only admins can view them

2024-07-04 21:16 UTC, shebz2023 approved these changes, later dismissed
LGTM

2024-07-05 02:35 UTC, Oliviier-dev submitted a review, later dismissed
LGTM

2024-07-05 11:37 UTC, SergeInGithub requested changes
Nice work @tuyishimekyrie Just work on some minor reviews below and you're good to go

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/Navbar.tsx
> +        </button>
We have a button component

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/Sidebar.tsx
> +              </button>
WE have a button component

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/ActionButton.tsx
> +      </button>
Button component instead

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/ActionButton.tsx
> +            </button>
Button component instead

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/RoleModal.tsx
> +          </button>
Here as well

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/RoleModal.tsx
> +      ></div>
```suggestion
      <div
        className="bg-black bg-opacity-50 absolute inset-0"
        onClick={onClose}
      />
```

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/RoleModal.tsx
> +          </button>
Button component instead

2024-07-05 11:37 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/RoleModal.tsx
> +        </button>
Here as well

2024-07-05 11:37 UTC, SergeInGithub commented on src/layouts/AdminLayout.tsx
Work on this as well

2024-07-05 12:49 UTC, SergeInGithub requested changes
Please finish all reviews! @tuyishimekyrie

2024-07-05 12:49 UTC, SergeInGithub commented on src/components/admincomponents/TableComponents/RoleModal.tsx
> +      ></div>
Can you work on this please!

2024-07-05 14:01 UTC, SergeInGithub approved these changes
LGTM

2024-07-05 14:01 UTC, merged