Ft buyer add items to cart 187364824
atlp-rwanda/e-commerce-serge-30-fn pull request #29
Opened 2024-07-08 06:49 UTC by tuyishimekyrie

## ℹ️ Description

Please write about the changes implemented in this PR. Also write a short description about why the change is implemented.

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-09 14:02 UTC, Aldot-02 reviewed
Geat Work @tuyishimekyrie,

Consider adding the tests for your new feature, screenshoots, as well as a simple demo of the feature working live.

2024-07-09 18:42 UTC, shebz2023 reviewed
Great work @tuyishimekyrie ,some suggestions below

2024-07-09 18:42 UTC, shebz2023 commented on src/components/rootcomponents/ShopProduct.tsx
> +      toast.error('Please Log In');
navigate('/auth/login')

2024-07-09 18:42 UTC, shebz2023 commented on src/components/rootcomponents/ShopProduct.tsx
> +    console.log(response);
remove consoles

2024-07-09 18:58 UTC, shebz2023 approved these changes, later dismissed
LGTM

2024-07-09 19:01 UTC, Aldot-02 approved these changes, later dismissed
LGTM

2024-07-09 20:01 UTC, SergeInGithub requested changes
Please work on the reviews provided by me and your teammates @tuyishimekyrie

2024-07-09 20:01 UTC, SergeInGithub commented on src/components/rootcomponents/ProductRow.tsx
> +            </button>
Why don't you use the button component we have?

2024-07-09 20:01 UTC, SergeInGithub commented on src/pages/rootpages/Cart.tsx
> +          </div>
This is a component. Stop repeating yourself

2024-07-10 16:52 UTC, SergeInGithub requested changes
Please work on the changes requested by your colleagues! @tuyishimekyrie

2024-07-11 07:15 UTC, SergeInGithub approved these changes
LGTM

2024-07-11 07:15 UTC, merged