ft(productDetails): Buyer adds ratings and feedback [#187364831]
atlp-rwanda/e-commerce-serge-30-fn pull request #30
Opened 2024-07-10 09:31 UTC by Oliviier-dev

## ℹ️ Description

This PR introduces the feature where the buyers who have purchased a product can be able to leave their feedbacks/reviews on the product; and also anyone who will visit the product page will be able to view all the reviews which were left.

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

This can be found under the product/:productID route

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-12 11:30 UTC, shebz2023 approved these changes, later dismissed
LGTM

2024-07-12 11:43 UTC, martinemahirwe approved these changes, later dismissed
LGTM

2024-07-12 14:05 UTC, SergeInGithub requested changes
Work on the reviews provided! @Oliviier-dev

2024-07-12 14:05 UTC, SergeInGithub commented on src/components/rootcomponents/ProductDetails.tsx
> +                </div>
```suggestion
  {product.image_url.slice(1, 4).map((url, index) => (
    <div key={index} className="h-fit w-24">
      <img src={url} alt={`${product.name} Image ${index + 1}`} />
    </div>
  ))}
```

2024-07-12 14:05 UTC, SergeInGithub commented on src/components/rootcomponents/ProductDetails.tsx
> +                  </div>
This is a component!

2024-07-12 14:05 UTC, SergeInGithub commented on src/pages/rootpages/AllProducts.tsx
> +            </div>
This is React, Why can't you make this a component? Why are you repeating yourself???

2024-07-15 20:23 UTC, SergeInGithub approved these changes
LGTM

2024-07-15 20:24 UTC, merged