ft(AddToWishlist): user add product to wishlist
atlp-rwanda/e-commerce-serge-30-fn pull request #31
Opened 2024-07-11 00:58 UTC by martinemahirwe

created the component for add product to wishlist functionality added functionality
wrote tests for testing the functionality for adding product to wishlist [delivers #187364828]

## ℹ️ Description

Please write about the changes implemented in this PR. Also write a short description about why the change is implemented.

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-12 09:45 UTC, Aldot-02 submitted a review, later dismissed
LGTM

2024-07-12 09:51 UTC, Oliviier-dev submitted a review, later dismissed
Nice work, @martinemahirwe , LGTM

2024-07-12 09:52 UTC, shebz2023 reviewed
Good work so far @martinemahirwe , some suggestions bellow, and its better to navigate users to login page when not logged in

2024-07-12 09:52 UTC, shebz2023 commented on src/components/rootcomponents/AddToWishlist.tsx
> +  const [addProductToWishlist, { isLoading, isSuccess, isError }] =
const [addProductToWishlist, { isLoading, isSuccess, isError ,error}]

2024-07-12 09:52 UTC, shebz2023 commented on src/components/rootcomponents/AddToWishlist.tsx
> +        'Failed to add product to wishlist. Please login and try again.',
toast.error(
        'Failed to add product to wishlist.' + error )

2024-07-12 11:13 UTC, shebz2023 approved these changes, later dismissed
LGTM

2024-07-12 11:18 UTC, Oliviier-dev submitted a review, later dismissed
LGTM

2024-07-12 14:19 UTC, SergeInGithub requested changes
1. Use a noticeable color for the wishlist button inside the image, you can also add some shadow around for it to be noticeable
2. Improve the UI design for the wishlist modal, You can find more inspiration online
3. Rebase. 

@martinemahirwe

2024-07-16 08:53 UTC, Oliviier-dev approved these changes
LGTM

2024-07-16 09:04 UTC, shebz2023 approved these changes
LGTM

2024-07-16 10:20 UTC, SergeInGithub approved these changes
LGTM

2024-07-16 10:20 UTC, merged