ft(Chat.tsx): user should be able to chat
atlp-rwanda/e-commerce-serge-30-fn pull request #33
Opened 2024-07-12 10:21 UTC by tuyishimekyrie

## ℹ️ Description

Please write about the changes implemented in this PR. Also write a short description about why the change is implemented.

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-14 14:00 UTC, shebz2023 reviewed
Good work @tuyishimekyrie  ,write some tests and the make the hover color on the sidebar look like the one of the selected

2024-07-14 15:19 UTC, Oliviier-dev approved these changes, later dismissed
LGTM

2024-07-14 16:14 UTC, shebz2023 submitted a review, later dismissed
LGTM

2024-07-14 16:30 UTC, Oliviier-dev submitted a review, later dismissed
LGTM

2024-07-15 20:41 UTC, SergeInGithub requested changes
Nice work so far @tuyishimekyrie You can try and improve the design of the chat a little. For example you can wrap each message in a card instead of just text. make the cards of the receiver and sender a different color and you can improve  Also, work on the suggestions below

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/rootpages/Cart.tsx
> +  // }
```suggestion
```

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/userpage/Chat.tsx
> +      <div className="w-full  rounded-lg   ">
```suggestion
      <div className="w-full  rounded-lg">
```

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/userpage/Chat.tsx
> +                <strong className="">
```suggestion
                <strong>
```

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/userpage/Chat.tsx
> +          <ul id="messages" className=" max-w-full  overflow-y-auto  h-[90vh] ">
```suggestion
          <ul id="messages" className=" max-w-full  overflow-y-auto  h-[90vh]">
```

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/userpage/Chat.tsx
> +    <div className="flex flex-col items-center justify-center min-h-screen text-white w-full ">
```suggestion
    <div className="flex flex-col items-center justify-center min-h-screen text-white w-full">
```

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/userpage/Chat.tsx
> +              className="flex-grow p-2 border border-gray-400 rounded-l-lg  text-black"
```suggestion
              className="flex-grow p-2 border border-gray-400 rounded-l-lg text-black"
```

2024-07-15 20:41 UTC, SergeInGithub commented on src/pages/userpage/Home.tsx
> +      {/* <h1 className="px-4">New Trend Style</h1> */}
```suggestion
```

2024-07-19 13:55 UTC, SergeInGithub submitted a review, later dismissed
LGTM. Just rebase and you're good to go

2024-07-20 13:07 UTC, SergeInGithub requested changes
Work on the reviews provided below @tuyishimekyrie

2024-07-20 13:07 UTC, SergeInGithub commented on src/pages/userPages/Chat.tsx
> +            </button>
we have a button component

2024-07-20 13:07 UTC, SergeInGithub commented on src/pages/userPages/Home.tsx
> +          </button>
we have an existing button component

2024-07-20 18:04 UTC, SergeInGithub approved these changes
LGTM

2024-07-20 18:04 UTC, merged