ft(userPage):A buyer should be able to checkout
atlp-rwanda/e-commerce-serge-30-fn pull request #34
Opened 2024-07-12 14:19 UTC by Ke-bean

## ℹ️ Description

Please write about the changes implemented in this PR. Also write a short description about why the change is implemented.

##### 📹 Loom video link: _URL here_

## 🧪 How can this be tested?

Write a short description on how others can test the changes implemented in the PR

## 📸 Screenshots

_Please add screenshots of the changes here._

## 📍 Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ✅ Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-16 08:25 UTC, Oliviier-dev reviewed
Nice work so far @Ke-bean look into these minor suggestions:

2024-07-16 08:25 UTC, Oliviier-dev commented on src/service/productApi.tsx
You can move this to the existing file with product endpoints located at src/service/productApi.ts

2024-07-16 08:25 UTC, Oliviier-dev commented on src/components/rootcomponents/CheckoutModal.tsx
> +              </label>
use an existing label component here

2024-07-16 08:25 UTC, Oliviier-dev commented on src/components/rootcomponents/CheckoutModal.tsx
> +              </label>
here as well, use an existing label component

2024-07-16 08:25 UTC, Oliviier-dev commented on src/components/rootcomponents/CheckoutModal.tsx
> +              </label>
and here

2024-07-16 09:06 UTC, Oliviier-dev approved these changes, later dismissed
LGTM

2024-07-16 09:10 UTC, martinemahirwe submitted a review, later dismissed
LGTM

2024-07-16 10:33 UTC, SergeInGithub requested changes
Have you really worked on the task as the description describes!! @Ke-bean 

<img width="490" alt="Screenshot 2024-07-16 at 12 32 33" src="https://github.com/user-attachments/assets/22fa0d17-ee5a-445d-8556-aebbe1cde2c1">

2024-07-17 13:27 UTC, Ke-bean commented
> > Have you really worked on the task as the description describes!! @Ke-bean
> > <img alt="Screenshot 2024-07-16 at 12 32 33" width="490" src="https://private-user-images.githubusercontent.com/110470861/349049361-22fa0d17-ee5a-445d-8556-aebbe1cde2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjE0NjksIm5iZiI6MTcyMTIyMTE2OSwicGF0aCI6Ii8xMTA0NzA4NjEvMzQ5MDQ5MzYxLTIyZmEwZDE3LWVlNWEtNDQ1ZC04NTU2LWFlYmJlMWNkZTJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxMjU5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzNjZDJhNGJlZjQ2N2Y3OTlmNjAzZWFiY2M0NzNmM2I4YjEwY2RjOTYyZmIzMzNjMDkwNmZkYmI0YTRkMzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mIxrY3EYIzIIv_HpKUKZ8cOZ0VAnqeV_2kMb8g5xGlI">
> 
> I figured out that I miss to redirect the customer to the payment portal but for the payment, it's a different task which is under development

2024-07-17 13:31 UTC, Ke-bean commented
> Have you really worked on the task as the description describes!! @Ke-bean
> 
> <img alt="Screenshot 2024-07-16 at 12 32 33" width="490" src="https://private-user-images.githubusercontent.com/110470861/349049361-22fa0d17-ee5a-445d-8556-aebbe1cde2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjMyMjksIm5iZiI6MTcyMTIyMjkyOSwicGF0aCI6Ii8xMTA0NzA4NjEvMzQ5MDQ5MzYxLTIyZmEwZDE3LWVlNWEtNDQ1ZC04NTU2LWFlYmJlMWNkZTJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxMzI4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODUyZjNkZGJkMDZmZDViZGEwMWVkODhlYzViN2ZmZDU4ZDg5ZmRmMmI2ZjA1NWU2MmU5MzhlMDY1MDc0MTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BDKuqLQvjPWtidxrT5W6jPP5_Y-BeY1NREtER46KFc">

I figured out that I missed the redirection of customer to the payment portal, but integrating payment is a different task which is under development

2024-07-18 10:22 UTC, martinemahirwe approved these changes
LGTM

2024-07-18 10:23 UTC, Oliviier-dev approved these changes
LGTM

2024-07-18 11:01 UTC, SergeInGithub approved these changes
LGTM

2024-07-18 11:01 UTC, merged