chore: Setup react router  (React-router-dom)[#187364797]
atlp-rwanda/e-commerce-serge-30-fn pull request #5
Opened 2024-06-12 12:44 UTC by andremugabo

This PR sets up React Router (react-router-dom) for the client application. It includes the installation and configuration of React Router, the creation of dummy routes for the login page and the home page (/), and the establishment of a components and views file structure.
1. Installation of React Router:
         - Installed react-router-dom and its TypeScript definitions.
         - Command used:
                 npm install react-router-dom @types/react-router-dom
2. Configuration of React Router:
         - Created a routes directory with an AppRoutes.tsx file to manage application routes
         - Configured AppRoutes with BrowserRouter, Routes, and Route components to handle navigation.
         - Added dummy routes for the home page (/) and the login page (/login).

2024-06-12 15:51 UTC, shebz2023 approved these changes
Great!

2024-06-13 06:42 UTC, tuyishimekyrie approved these changes
LGTM

2024-06-13 08:32 UTC, SergeInGithub requested changes
Look into the changes suggested below @andremugabo

2024-06-13 08:32 UTC, SergeInGithub commented on src/routes/AppRoutes.tsx
> +        </Router>
This is good but there's a new way for routing which separates the main app from routes. It also has features like data loading, deferred loading out of the box, etc... look into it, hint: it uses createBrowserRouter and createRoutesFromElements

2024-06-13 08:32 UTC, SergeInGithub commented on src/routes/AppRoutes.tsx
> +import React from 'react';
rename this file to routes.tsx and export it * in the index.ts file that you have to create in the routes folder

2024-06-13 08:32 UTC, SergeInGithub commented on src/views/HomePage.tsx
> +import React from 'react';
Rename views to pages and export homepage as regular not default, then export it from the index file in the pages folder

2024-06-13 08:32 UTC, SergeInGithub commented on src/App.tsx
> +    return <AppRoutes />;
use RouterProvider from react-router-dom instead

2024-06-13 13:31 UTC, SergeInGithub requested changes
Address the changes below @andremugabo

2024-06-13 13:31 UTC, SergeInGithub commented on src/routes/routes.tsx
> +    <Route path="/" element={<App />}>
Create a file called `RootLayout` in the layouts folder then export it in the index file there
```suggestion
    <Route path="/" element={<RootLayout />}>
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/routes/routes.tsx
> +const router = createBrowserRouter(
```suggestion
export const router = createBrowserRouter(
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/routes/routes.tsx
> +export default router;
```suggestion
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/routes/index.ts
> +export default router;
```suggestion
export * from './routes';
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/pages/index.ts
> +export { default as NotFoundPage } from './NotFoundPage';
```suggestion
export * from './Home';
export * from './LoginPage';
export * from './NotFoundPage';
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/pages/NotFoundPage.tsx
> +const NotFoundPage: React.FC = () => {
```suggestion
export function NotFoundPage() {
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/pages/NotFoundPage.tsx
> +export default NotFoundPage;
```suggestion
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/pages/LoginPage.tsx
> +const LoginPage: React.FC = () => {
```suggestion
export function LoginPage() {
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/pages/LoginPage.tsx
> +export default LoginPage;
```suggestion
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/pages/Home.tsx
> +export const HomePage: React.FC = () => {
```suggestion
export function HomePage() {
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/main.tsx
>    <React.StrictMode>
```suggestion
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/components/Header.tsx
> +const Header: React.FC = () => {
```suggestion
export const Header: React.FC = () => {
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/components/Header.tsx
> +export default Header;
```suggestion
```

2024-06-13 13:31 UTC, SergeInGithub commented on src/components/Header.tsx
> +
create an index file in the components folder and export like i've shown you on other index files below

2024-06-13 13:31 UTC, SergeInGithub commented on src/App.tsx
> +    </div>
```suggestion
    <Provider store={store}>
        <RouterProvider router={router} />
    </Provider>
```

2024-06-14 09:10 UTC, SergeInGithub approved these changes
Nice work @andremugabo

2024-06-14 09:10 UTC, merged