ch(store.ts): Setup redux toolkit for global state management[#187364794]
atlp-rwanda/e-commerce-serge-30-fn pull request #6
Opened 2024-06-12 13:43 UTC by martinemahirwe

##Configured the Redux store using Redux Toolkit

1.Created slices folder
2.Provided the redux store into the react app
3.Created custom hooks for useSelector and useDispatch with predefined types to avoid assigning types repeatedly
 [Delivers #187364794]

2024-06-12 16:46 UTC, tuyishimekyrie approved these changes
LGTM

2024-06-12 20:16 UTC, Aldot-02 approved these changes
LGTM

2024-06-13 07:03 UTC, SergeInGithub requested changes
Some reviews below @martinemahirwe Also rebase your branch

2024-06-13 07:03 UTC, SergeInGithub commented on src/main.tsx
> +    <Provider store = {store}>
You can put this provider in the App.tsx file instead

2024-06-13 07:03 UTC, SergeInGithub commented on src/Hooks.ts
> +export const useAppSelector = useSelector.withTypes<RootState>();
Create a hooks folder then and index.ts file inside that will export hooks in that folder. In the hooks folder you can then create a file for this then export everything from the index file

2024-06-13 08:39 UTC, SergeInGithub approved these changes
LGTM

2024-06-13 08:39 UTC, merged